theme: jekyll-theme-minimal
title: Adéla Šubrtová
logo: /assets/imgs/photo.jpeg
description: I am a PhD student in the <a href="https://cyber.felk.cvut.cz/research/groups-teams/vrg/">Visual Recognition Group (VRG)</a> at CTU in Prague supervised by Jan Čech and Jiří Matas (supervisor specialist).
contact:
  email: subrtade (at) fel.cvut.cz
  cv: https://drive.google.com/file/d/19p_wZB7nVuVwZhxK3pLRN9qkIN4mvLWZ/view?usp=share_link
  linkedin: https://www.linkedin.com/in/subrtade/
  scholar: https://scholar.google.cz/citations?hl=cs&user=0UVpQA0AAAAJ&view_op=list_works&gmla=AKKJWFe94dSdUeetQtuGqFvL5ndWOf2aUeJR_Dzsug0bMEm0x8ymlo5oBdSFkzl5bQTw8WCoRcdLC-Zg_zhO47on70iAullSIWBb
